# Generated by Django 3.2.3 on 2021-06-15 09:23

import data_visualization.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=data_visualization.models.file_name)),
                ('user_id', models.UUIDField(default=uuid.UUID('45aacc6d-cdbb-11eb-8201-b89a2a687c94'))),
                ('time', models.DateTimeField(default='2021-06-15T11:22:57.633188')),
            ],
        ),
    ]
