# Generated by Django 3.2.3 on 2021-06-16 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0002_auto_20210615_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-16T22:31:38.153436'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('d9c61a9d-cee1-11eb-98a4-04ed33e929ca')),
        ),
    ]
