# Generated by Django 3.2.3 on 2021-06-17 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0002_auto_20210615_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-17T11:17:35.124399'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('da4334a8-cf4c-11eb-b907-b89a2a687c97')),
        ),
    ]
