# Generated by Django 3.2.3 on 2021-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0003_auto_20210616_2231'),
        ('data_visualization', '0003_auto_20210617_1117'),
    ]

    operations = [
    ]
