# Generated by Django 3.2.3 on 2021-06-18 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0004_merge_0003_auto_20210616_2231_0003_auto_20210617_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-18T13:51:14.149562'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('7ba4b74d-d02b-11eb-b6c5-b89a2a687c97')),
        ),
    ]
