# Generated by Django 3.2.3 on 2021-06-18 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_visualization', '0005_auto_20210618_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.UUID('18b5f838-d05f-11eb-ba57-b89a2a687c97'))),
            ],
        ),
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-18T20:00:41.998136'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('18b5f838-d05f-11eb-ba57-b89a2a687c97')),
        ),
    ]
