# Generated by Django 3.2.3 on 2021-06-15 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=uuid.UUID('3bd880de-cdbb-11eb-869d-b89a2a687c94'), max_length=255)),
            ],
        ),
    ]
