# Generated by Django 3.2 on 2021-05-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_set',
            old_name='path',
            new_name='data',
        ),
    ]
