# Generated by Django 3.2.3 on 2021-06-16 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('d9c61a9d-cee1-11eb-98a4-04ed33e929ca'), max_length=255),
        ),
    ]
