<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-06-16 20:31
=======
# Generated by Django 3.2.3 on 2021-06-17 09:17
>>>>>>> e82503742eb0984c187cde6e22a9c1ade99dfd42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
<<<<<<< HEAD
            field=models.CharField(default=uuid.UUID('d9c61a9d-cee1-11eb-98a4-04ed33e929ca'), max_length=255),
=======
            field=models.CharField(default=uuid.UUID('da4334a8-cf4c-11eb-b907-b89a2a687c97'), max_length=255),
>>>>>>> e82503742eb0984c187cde6e22a9c1ade99dfd42
        ),
    ]
