# Generated by Django 3.2.3 on 2021-06-17 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('da4334a8-cf4c-11eb-b907-b89a2a687c97'), max_length=255),
        ),
    ]
