# Generated by Django 3.2 on 2021-05-10 08:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_path_data_set_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='data',
            field=models.FileField(max_length=255, upload_to=main.models.file_name),
        ),
    ]
