# Generated by Django 3.2.3 on 2021-06-18 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('7ba4b74d-d02b-11eb-b6c5-b89a2a687c97'), max_length=255),
        ),
    ]
