# Generated by Django 3.2 on 2021-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_set_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='data',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
