# Generated by Django 3.2.3 on 2021-06-18 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('18b5f838-d05f-11eb-ba57-b89a2a687c97'), max_length=255),
        ),
    ]
