# Generated by Django 3.2 on 2021-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_data_set_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='b43fa0bf-b22d-11eb-a376-b89a2a687c94', max_length=255),
        ),
    ]
