# Generated by Django 3.2 on 2021-05-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210511_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='86f1bab9-b239-11eb-9d64-b89a2a687c94', max_length=255),
        ),
    ]
