# Generated by Django 3.2.3 on 2021-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_data_set_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_set',
            old_name='data',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='789018d3-ba1d-11eb-bf25-b89a2a687c97', max_length=255),
        ),
    ]
