# Generated by Django 3.2.3 on 2021-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210521_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='8a918e06-bfb2-11eb-9ed0-b89a2a687c97', max_length=255),
        ),
    ]
