# Generated by Django 3.2.3 on 2021-06-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_data_set_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_set',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 4, 10, 16, 28, 6251)),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='291eca2f-c50d-11eb-b4c1-b89a2a687c97', max_length=255),
        ),
    ]
