# Generated by Django 3.2.3 on 2021-06-04 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210604_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 10, 45, 54, 547537)),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='460f7241-c511-11eb-a9e7-b89a2a687c97', max_length=255),
        ),
    ]
