# Generated by Django 3.2.3 on 2021-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210604_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-04T14:00:56.226807'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='84ce27aa-c52c-11eb-a7a3-b89a2a687c94', max_length=255),
        ),
    ]
