# Generated by Django 3.2.3 on 2021-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210610_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='time',
            field=models.DateTimeField(default='2021-06-10T21:14:02.426783'),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='0444183f-ca20-11eb-8f1d-b89a2a687c97', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='0444183f-ca20-11eb-8f1d-b89a2a687c97', max_length=255),
        ),
    ]
