# Generated by Django 3.2 on 2021-05-11 09:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_data_set_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='data',
            field=models.FileField(max_length=255, upload_to=main.models.file_name),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='323378e3-b238-11eb-baa1-b89a2a687c94', max_length=255),
        ),
    ]
