# Generated by Django 3.2 on 2021-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_data_set_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='user_id',
            field=models.CharField(default='2dcaaa98-b23a-11eb-8d11-b89a2a687c94', max_length=255),
        ),
    ]
